name: PR
run-name: Testing ${{github.event.pull_request.title}}
on: [pull_request, workflow_call]
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: testing
        run: npm run test:unit:ci
  integration-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: testing
        run: npm run test:e2e:ci
