name: Release
run-name: Realising ${{github.ref_name}}
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
  issues: write
jobs:
  test:
    uses: ./.github/workflows/onpr.yml
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{github.token}}
          tag: ${{github.ref_name}}
      - name: Concatenate changelog
        run: cat CHANGELOG.md >> .github/ISSUE_TEMPLATE.md
      - name: Create issue
        id: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          name: ${{github.ref_name}}
        with:
          update_existing: true
          search_existing: all
          assignees: ${{github.actor}}
