name: Testing
on:
  push:
    branches:
      - "master"
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: testing
        run: npm run test
  integration-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx playwright install
      - name: testing
        run: npm run e2e
